export const CartActions = {
    TOOGLE_CARD_HIDDEN: "TOOGLE_CARD_HIDDEN",
    ADD_ITEM: "ADD_ITEM",
    CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
    REMOVE_ITEM: "REMOVE_ITEM",
    CLEAR_CART: 'CLEAR_CART'
}